/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminUserPanel: typeof import('./components/AdminUserPanel.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FotosFinalizacaoModal: typeof import('./components/FotosFinalizacaoModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RfbSealingModal: typeof import('./components/RfbSealingModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignatureModal: typeof import('./components/SignatureModal.vue')['default']
    UserProfilePanel: typeof import('./components/UserProfilePanel.vue')['default']
  }
}
