/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/inspections/[id]/': RouteRecordInfo<'/inspections/[id]/', '/inspections/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/inspections/[id]/finalize': RouteRecordInfo<'/inspections/[id]/finalize', '/inspections/:id/finalize', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/inspections/[id]/report': RouteRecordInfo<'/inspections/[id]/report', '/inspections/:id/report', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/inspections/new': RouteRecordInfo<'/inspections/new', '/inspections/new', Record<never, never>, Record<never, never>>,
  }
}
